### ISSUE TITLE
dev-java/httpcore-4.4.14 fails tests

### ISSUE THREAD

**Issue by asarubbo** [2Kmm/java#12]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-java/httpcore-4.4.14 fails tests.
Discovered on: amd64 (internal ref: java-test_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0015

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/cd3f4da8380bd230e7d72cfef81b778b
Context of error(s): https://gist.github.com/asarubbo/c88b7f7cfa4d0a719c5cf4d6e00e32c0

**Comment by vaukai** [comment]
old version has gone. https://packages.gentoo.org/packages/dev-java/httpcore/changelog
