### ISSUE TITLE
dev-java/jcommander-1.82 fails tests

### ISSUE THREAD

**Issue by asarubbo** [2Kmm/java#13]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-java/jcommander-1.82 fails tests.
Discovered on: amd64 (internal ref: java-test_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0015

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/741d873eccfb1cca8d18d00ecc96293c
Context of error(s): https://gist.github.com/asarubbo/4641cec55bf4674d1921ae35804b1fa1

**Comment by vaukai** [comment]
unrelated, happens also on ::gentoo.
guess that `jcommander-1.82` might need a `testng` version built same version of `jcommander`. however `testng-6.11` needs version `1.64`.
i have https://github.com/gentoo/gentoo/compare/master...vaukai:testng-7.5.1 abandoned time ago
