### ISSUE TITLE
dev-java/java-service-wrapper-3.5.50-r1 fails to compile: environment: line 1326: xml-rewrite-3.py: No such file or directory 

### ISSUE THREAD

**Issue by asarubbo** [2Kmm/java#16]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-java/java-service-wrapper-3.5.50-r1 fails to compile.
Discovered on: amd64 (internal ref: java-test_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0014

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/0713288a555022bfecc6fb78d8f654a4

**Comment by 2Kmm** [comment]
Seems unrelated to changes in `java-pkg-simple.eclass` - closing
